print("Welcome to the tip calculator")
total_bill = float(input("What was the total bill?" ))
tip= int(input("What percentage tip would you like to give? 10,12, or 15?"))
no_of_people = int(input("How many people to split the bill?"))
bill_plus_tip= total_bill + ((tip * total_bill)/100)
each_person_pay = round((bill_plus_tip/no_of_people),2)
print(f"Each person should pay: {each_person_pay}")